; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = LED
; default_envs = LCD
; default_envs = SDCard
; default_envs = Factory
; default_envs = wifi_serial
default_envs = wifi_repeater

lib_dir = ./lib
boards_dir = ./board
src_dir = examples/${platformio.default_envs}

[env]
platform = https://github.com/pioarduino/platform-espressif32.git #develop
board = Lilygo-T-Dongle-C5
framework = arduino
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
extra_scripts = post:extra_script.py  # <-- 新增这行

[env:LED]
extends = env
build_flags = 
	${env.build_flags}
	
[env:LCD]
extends = env
build_flags = 
	${env.build_flags}
	
[env:SDCard]
extends = env
build_flags = 
	${env.build_flags}

[env:wifi_serial]
extends = env
build_flags =
	${env.build_flags}
	
[env:wifi_repeater]
extends = env
build_flags =
	${env.build_flags}

[env:Factory]
extends = env
build_flags =
	${env.build_flags}